find_path(SOIL_INCLUDE_DIR NAMES SOIL.h PATHS {CONAN_INCLUDE_DIRS_SOIL} NO_CMAKE_FIND_ROOT_PATH)
find_library(SOIL_LIBRARY NAMES ${CONAN_LIBS_SOIL} PATHS ${CONAN_LIB_DIRS_SOIL} NO_CMAKE_FIND_ROOT_PATH)

message(STATUS "** SOIL ALREADY FOUND BY CONAN!")
message(STATUS "** FOUND SOIL: ${SOIL_LIBRARY}")
message(STATUS "** FOUND SOIL INCLUDE: ${SOIL_INCLUDE_DIR}")

set(SOIL_FOUND TRUE)
set(SOIL_INCLUDE_DIRS ${SOIL_INCLUDE_DIR})
set(SOIL_LIBRARIES ${SOIL_LIBRARY})

mark_as_advanced(SOIL_LIBRARY SOIL_INCLUDE_DIR)
